const services = [
    {
        _id: '1',
        title: 'Dog Walking',
        category: 'Pet Services',
        image: new URL('../assets/img/ServiceImg/DogWalking1.jpg', import.meta.url).href,
        description: 'Connecting pet lovers with local dog walkers.',
    },
    {
        _id: '2',
        title: 'Babysitting',
        category: 'Child and Elderly Care',
        image: new URL('../assets/img/ServiceImg/BabySitting1.jpg', import.meta.url).href,
        description: 'Linking families with caregivers seeking part-time jobs.',
    },
    {
        _id: '3',
        title: 'Elderly Care',
        category: 'Child and Elderly Care',
        image: new URL('../assets/img/ServiceImg/ElderlyCare1.jpg', import.meta.url).href,
        description: 'Helping families find caregivers for elderly relatives.',
    },
    {
        _id: '4',
        title: 'Home Cleaning',
        category: 'Home Services',
        image: new URL('../assets/img/ServiceImg/HomeCleaning1.jpg', import.meta.url).href,
        description: 'Facilitating cleaning services from individuals.',
    },
    {
        id: 5,
        title: 'Handyman Services',
        category: 'Home Services',
        image: new URL('../assets/img/ServiceImg/Plumbing1.jpg', import.meta.url).href,
        description: 'Providing a platform for skilled individuals offering minor repairs.',
    },
    {
        _id: '6',
        title: 'Gardening',
        category: 'Home Services',
        image: new URL('../assets/img/ServiceImg/Gardening1.jpg', import.meta.url).href,
        description: 'Providing services for lawn maintenance and landscaping.',
    },
    {
        _id: '7',
        title: 'Home Organization',
        category: 'Home Services',
        image: new URL('../assets/img/ServiceImg/HomeCleaning2.jpg', import.meta.url).href,
        description: 'Helping clients declutter and organize their spaces.',
    },
    {
        _id: '8',
        title: 'Moving and Packing Help',
        category: 'Home Services',
        image: new URL('../assets/img/ServiceImg/FurnitureAssembly2.jpg', import.meta.url).href,
        description: 'Assisting users with furniture moving and packing.',
    },
    {
        id: 9,
        title: 'Tutoring',
        category: 'Educational Services',
        image: new URL('../assets/img/ServiceImg/Tutoring1.jpg', import.meta.url).href,
        description: 'Connecting students with local tutors for academic assistance.',
    },
    {
        _id: '10',
        title: 'Music Lessons',
        category: 'Educational Services',
        image: new URL('../assets/img/ServiceImg/MusicLessons.jpg', import.meta.url).href,
        description: 'Offering lessons for aspiring musicians.',
    },
    {
        _id: '11',
        title: 'Photography',
        category: 'Freelance and Creative Services',
        image: new URL('../assets/img/ServiceImg/Photographer1.jpg', import.meta.url).href,
        description: 'Linking amateur photographers with clients needing professional photos.',
    },
    {
        _id: '12',
        title: 'Event Planning',
        category: 'Freelance and Creative Services',
        image: new URL('../assets/img/ServiceImg/EventPlanning.jpg', import.meta.url).href,
        description: 'Connecting users with freelance event planners for parties and weddings.',
    },
    {
        _id: '13',
        title: 'Home Cooking',
        category: 'Food and Cooking Services',
        image: new URL('../assets/img/ServiceImg/HomeCooking1.jpg', import.meta.url).href,
        description: 'Allowing home cooks to provide prepared meals.',
    },
    {
        _id: '14',
        title: 'Delivery Services',
        category: 'Food and Cooking Services',
        image: new URL('../assets/img/ServiceImg/DeliveryServices.jpg', import.meta.url).href,
        description: 'Enabling users to deliver food or goods locally.',
    },
    {
        _id: '15',
        title: 'Fitness Training',
        category: 'Health and Fitness Services',
        image: new URL('../assets/img/ServiceImg/PhysicalCoach1.jpg', import.meta.url).href,
        description: 'Enabling trainers to offer personalized sessions.',
    },
    {
        _id: '16',
        title: 'Beauty Services',
        category: 'Health and Fitness Services',
        image: new URL('../assets/img/ServiceImg/BeautyServices.jpg', import.meta.url).href,
        description: 'Connecting clients with professionals for personal care services.',
    },
    {
        _id: '17',
        title: 'Virtual Assistance',
        category: 'Support Services',
        image: new URL('../assets/img/ServiceImg/VirtualAssistance.jpg', import.meta.url).href,
        description: 'Offering administrative support from home.',
    },
    {
        _id: '18',
        title: 'Tech Support',
        category: 'Support Services',
        image: new URL('../assets/img/ServiceImg/TechSupport.jpg', import.meta.url).href,
        description: 'Providing assistance with troubleshooting devices.',
    },
    {
        _id: '19',
        title: 'Car Washing',
        category: 'Vehicle Services',
        image: new URL('../assets/img/ServiceImg/CarWashing1.jpg', import.meta.url).href,
        description: 'Connecting car enthusiasts with customers needing detailing services.',
    },
    {
        _id: '20',
        title: 'Bike Repair',
        category: 'Vehicle Services',
        image: new URL('../assets/img/ServiceImg/BikeRepair.jpg', import.meta.url).href,
        description: 'Catering to cyclists with local bike repair services.',
    },
];

export default services; // Export the services array